### ISSUE TITLE
BRC-20 Display in the Ordinals Explorer

### ISSUE THREAD

**Issue by smcclellan** [hirosystems/ordinals-explorer#75]
User stories:
- [x] I want to view a full or partial list of BRC-20 tokens
- [x] I want to understand the time a BRC-20 token was deployed
- [x] I want to understand the total supply of a BRC-20 token
- [x] I want to understand the number of BRC-20 tokens minted (against supply)
- [x] I want to search for BRC-20 tokens by name

Nice to have additions:
- [ ] #90
- [x] I want to understand the time a BRC-20 token was completed
- [x] ~~I want to understand if a BRC-20-syntax inscription is valid BRC-20~~

**Comment by smcclellan** [comment]
Note: Rather than create issues for each of the user stories, we will track them here as checkboxes in the issue description and have any decomposed issues be created to break up the development work.
